version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules   # (Remove or comment this out to use container's node_modules)
    command: npm run dev
    env_file:
      - .env
