version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
    command: ["sh", "-c", "npm install && npx next dev"]
    env_file:
      - .env
