version: "3.8"

services:
  web:
    image: iimpossible-web-app:latest  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npx next dev"]
    env_file:
      - .env
